### ISSUE TITLE
wyy你的api正常，但是自己部署了发现有一些bug

### ISSUE THREAD

**Issue by kingrmb** [Superheroff/musicapi#4]
<img width="942" alt="image" src="https://github.com/Superheroff/musicapi/assets/124293662/a6464db5-f869-4ba2-bb81-8ffd556b46d6">

@Superheroff

**Comment by Superheroff** [comment]
> <img width="942" alt="image" src="https://github.com/Superheroff/musicapi/assets/124293662/a6464db5-f869-4ba2-bb81-8ffd556b46d6">
> 
> 
> 
> 
> 
> @Superheroff 

嗯嗯好

**Comment by Superheroff** [comment]
已修复
